config/routes.rb
Rails.application.routes.draw do
  root 'issues#index'
  devise_for :users
  get 'welcome/index'
  resources :issues

  resources :users
  resources :favorites

  resources :issues do
  resources :buses

end

get "/busroutes", to: "buses#api"
end

  

  

  

app/models/bus.rb
class Bus < ActiveRecord::Base
  has_many :issue
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :bus
	belongs_to :user
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites
  has_many :issues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
	include HTTParty
	
	def new
    	@bus = Bus.find_or_create_by(bus_id: bus_id)
  	end

  	def api
  		@api_key = ENV["api_key"]
  		@url = HTTParty.get("https://api.wmata.com/Bus.svc/json/jRoutes?api_key=#{@api_key}")
  		render :json => {url: @url}
  	
  	end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.new(favorite_params)

    @favorite.user = current_user
    
    if @favorite.save
    	redirect_to :back
    end
  end

  def destroy 
    @favorite = Favorite.find(params[:favorite])
    @favorite.destroy
  end

  private

  def favorite_params
  	params.require(:favorite).permit(:busroute)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!


  def index
    @issue = Issue.new
    @issues = Issue.all.order("created_at desc").each 
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @issue = Issue.new
    @issues = Issue.where(route: params[:route])
    @favorite = Favorite.new
    @favorite.busroute = params[:route]
  end


  def edit
    @issue = Issue.find(params[:id])
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to issues_path
    else
      render 'new'
    end
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update(issue_params)
      redirect_to @issue
    else
      render 'edit'
    end
  end

  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy
    redirect_to issues_path
  end

  private
  def issue_params
    params.require(:issue).permit(:title, :text, :route, :user_id, :timestamp)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/index.html.erb
<%= form_for @issue, method: "GET", url: new_issue_path do |f| %>
  
  <select name="route" id="favoritesdropdown">
    <option value="">Favorites</option>

  </select>
  
  <%= f.submit "Save as favorite" %>
<% end %>

app/views/issues/_form.html.erb
<%= form_for @issue do |f| %>
 
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@issue.errors.count, "error") %> prohibited
        this issue from being saved:
      </h2>
      <ul>
        <% @issue.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
   
    <%= f.hidden_field :route, :value => params[:route] %>

      <%= f.hidden_field :user_id, :value => current_user.id %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  <p>
<button><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></button>
</p>


 
<% end %>

app/views/issues/edit.html.erb
<h2>Editing issue</h2>
 
<%= render 'form' %>
 
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h2>WhatsaMATA with WMATA buses? Report your experiences!</h2>

 
<%= form_for @issue, method: "GET", url: new_issue_path do |f| %>
  <select name="route" id="busdropdown">
    <option value="">Choose Your Route</option>
  </select>
  <%= f.submit "Submit an issue" %>
<% end %>


<%= form_for @issue, method: "GET", url: new_issue_path do |f| %>
  <select name="route" id="favoritesdropdown">
    <option value="">Favorites</option>
    <% current_user.favorites.each do |favorite| %>
    <option><%= favorite.busroute %></option>
  <% end %>
  </select>
  <%= f.submit "Submit an issue" %>
<% end %>
<p>
<button><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></button>
</p>

<p>
 
<table class="issuetable">
  <tr>
    <th>Bus Route</th>
    <th>Issue</th>
    <th>Summary</th>
    
     <th colspan="3"></th>
  </tr>
 
  <% @issues.each do |issue| %>
    <tr>
      <td><%= issue.route %></td>
      <td class="width"><%= issue.title %></td>
      <td class="width"><%= issue.text %> <br><i><font size="2"><%= issue.created_at.strftime("posted on %B %d at %I:%M %p") %></i></font></td>

      <td><%= link_to 'View', issue_path(issue) %></td>
      <% if issue.user == current_user %>
      <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
      <td><%= link_to 'Delete', issue_path(issue),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
              <% else %><td colspan="3"> </td> 
              <% end %>
    </tr>
  </p>
  <% end %>
</table>

app/views/issues/new.html.erb
<h2>New Issue</h2>

<%= form_for @favorite do |f| %>
  <%= f.text_field :busroute %>
  <%= f.submit "Save this route as a favorite", :class => "button", :onclick => "alert('Route favorited')" %>
 


<% end %>


<%= render 'form' %>
<table class="issuetable">
   <tr>
    <th>Bus Route</th>
    <th>Issue</th>
    <th>Summary</th>
    
     <th colspan="3"></th>
  </tr>
  <% @issues.each do |issue| %>
    <tr>
      <td><%= issue.route %></td>
      <td class="width"><%= issue.title %></td>
      <td class="width"><%= issue.text %> <br><i><font size="2"><%= issue.created_at.strftime("posted on %B %d at %I:%M %p") %></i></font></td>

      <td><%= link_to 'View', issue_path(issue) %></td>
      <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
      <td><%= link_to 'Delete', issue_path(issue),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


 
<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @issue.text %>
</p>


 
<%= link_to 'Back', issues_path %>
|
<%= link_to 'Edit', edit_issue_path(@issue) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whatsamata</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= stylesheet_link_tag    'application', "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="banner">

<div class="textbackground"><h1>WhatsaMATA<%#= link_to 'WhatsaMATA', issues_path %> </h1></div>


</div>


<%= yield %>


<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/welcome/index.html.erb
<p>
<%= link_to 'See recent issues', controller: 'issues' %></p>